name: Build sdk-bindings for Wasix
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
  workflow_call:
    inputs:
      repository:
        description: 'sdk repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      use-dummy-binaries:
        description: 'If true, creates dummy binaries rather than real binaries'
        required: false
        type: boolean
        default: false

jobs:
  build:
    if: ${{ !inputs.use-dummy-binaries }}
    runs-on: ubuntu-22.04
    name: build ${{ matrix.target }}
    strategy:
      matrix:
        target: [
          wasm32-wasmer-wasi,
        ]
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with: 
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository || github.repository }}

    - name: Install build-essential
      run: sudo apt update && sudo apt install -y build-essential

    - name: Install wasm-sdk
      working-directory: /opt
      env:
        WASI_MAJOR_VERSION: 20
        WASI_MINOR_VERSION: 0
      run: |
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-$WASI_MAJOR_VERSION/wasi-sdk-$WASI_MAJOR_VERSION.$WASI_MINOR_VERSION-linux.tar.gz
        tar xvf wasi-sdk-$WASI_MAJOR_VERSION.$WASI_MINOR_VERSION-linux.tar.gz
        mv wasi-sdk-$WASI_MAJOR_VERSION.$WASI_MINOR_VERSION wasi-sdk

    - name: Install rust toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"
        rustup set auto-self-update disable
        rustup toolchain install stable 
        rustup target add wasm32-wasi
        sudo apt install -y linux-headers-generic

    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "23.4"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: libs

    - name: Install wasix
      run: |
        sudo apt-get install -y curl wget xz-utils git python3 ninja-build cmake
        $HOME/.cargo/bin/cargo install cargo-wasix --git https://github.com/dangeross/cargo-wasix --branch main
        $HOME/.cargo/bin/cargo wasix download-toolchain

    - name: Build sdk-wasm
      working-directory: libs/sdk-wasm
      env:
        WASI_SDK: /opt/wasi-sdk
        AR: /opt/wasi-sdk/bin/llvm-ar
        NM: /opt/wasi-sdk/bin/llvm-nm
        CC: /opt/wasi-sdk/bin/clang
        CXX: /opt/wasi-sdk/bin/clang++
      run: $HOME/.cargo/bin/cargo wasix build --release
    
    - name: Archive release
      uses: actions/upload-artifact@v3
      with:
        name: sdk-bindings-${{ matrix.target }}
        path: libs/sdk-wasm/target/${{ matrix.target }}/release/breez_sdk_wasm.wasm

  build-dummies:
    if: ${{ inputs.use-dummy-binaries }}
    runs-on: ubuntu-latest
    name: build wasix dummies
    strategy:
      matrix:
        target: [
          wasm32-wasmer-wasi,
        ]
    steps:
      - name: Build dummy wasix ${{ matrix.target }}
        run: |
          touch breez-sdk-wasm.wasm

      - name: Upload dummy wasix ${{ matrix.target }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdk-bindings-${{ matrix.target }}
          path: ./*
