name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ main ]
  pull_request:    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd libs
          cargo fmt -- --check
          cd ../tools/sdk-cli
          cargo fmt -- --check

  build:

    runs-on: macOS-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: install dependencies
        run: |
          echo $ANDROID_NDK_HOME
          cargo install cargo-ndk@2.12.2
          cargo install --version 0.22.0 uniffi_bindgen          
          brew install protobuf          

      - name: run lib tests
        env:
          SSH_PRIVATE_KEY: ${{secrets.REPO_SSH_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          curl -o jna-5.12.1.jar https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
          export CLASSPATH=$(pwd)/jna-5.12.1.jar;
          cd libs
          cargo test  
      
      - name: run tools tests        
        run: |
          cd tools/sdk-cli
          cargo test

      - name: clippy
        run: |
          cd libs
          # Explicitly allow clippy::uninlined-format-args lint because it's present in the generated breez_sdk.uniffi.rs
          cargo clippy -- -D warnings -A clippy::uninlined-format-args
          cargo clippy --tests -- -D warnings -A clippy::uninlined-format-args
          cd ../tools/sdk-cli
          cargo clippy -- -D warnings